services:
  client:
    build:
      context: .
      target: nginx-client
    ports:
      - '80:80'
    networks:
      - app-network

  server:
    build:
      context: .
      target: node-server
    ports:
      - '3004:3004' 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
